# Ref https://goreleaser.com

version: 1

before:
  hooks:
    - go mod tidy
    - go vet ./...
    - go test -mod=mod -v ./...

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_{{- .Os }}_{{ .Tag }}_{{ .Arch }}{{- if .Arm }}v{{ .Arm }}{{ end }}

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
