# Ref: https://goreleaser.com/ci/actions/

name: goreleaser
on:
  push:
    # run only against tags
    tags:
      - "v*.*.*"
permissions:
  # needed to create releases
  contents: write
jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.20'

    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v5
      with:
        distribution: goreleaser
        version: latest
        args: release --clean

      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
