name: build_and_test
on:
  push:
  pull_request:
jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup Go
      uses: actions/setup-go@v1
      with:
        go-version: '1.20'

    - name: GoReleaser
      uses: goreleaser/goreleaser-action@v5
      with:
        version: latest
        args: release --snapshot --clean
